name: helloworld
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  async: any
  convert: ^3.1.2
  dart_oncrpc: ^1.0.1
  grpc: ^4.3.1
  protobuf: ^5.0.0

dev_dependencies:
  lints: ^6.0.0